version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: bmchristmascake-db
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bmchristmascake
      MYSQL_USER: yoshi
      MYSQL_PASSWORD: 1234
      TZ: "Asia/Tokyo"
    volumes:
      - bmchristmascake_mysql_data:/var/lib/mysql
    networks:
      - bmchristmascake-backend

  backend:
    build: ./backend
    container_name: bmchristmascake-backend
    restart: always
    environment:
      - DB_HOST=db 
      - DB_USER=yoshi
      - DB_PASSWORD=1234
      - DB_NAME=bmchristmascake
      - VIRTUAL_HOST=api.christmascake.beurre-mou.com
      - VIRTUAL_PORT=3001
      - LETSENCRYPT_HOST=api.christmascake.beurre-mou.com
    depends_on:
      - db
    networks:
      - bmchristmascake-backend
      - beurre_mou_proxy-tier

  frontend:
    build: ./frontend
    container_name: bmchristmascake-frontend
    restart: always
    environment:
      - VIRTUAL_HOST=christmascake.beurre-mou.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=christmascake.beurre-mou.com
    networks:
      - bmchristmascake-backend
      - beurre_mou_proxy-tier

volumes:
  bmchristmascake_mysql_data:

networks:
  bmchristmascake-backend:
    driver: bridge
  beurre_mou_proxy-tier:
    external: true